# say-hello/src/Inanzzz/HelloBundle/Resources/config/services.yml

services:
    inanzzz_hello.util.hello:         #inanzzz_hello must match DependencyInjection/Configuration.php line $treeBuilder->root('xxxxxxxx');
        class: Inanzzz\HelloBundle\Util\Hello